all : 8-9_rec.cpp 8-9_dp.cpp
	g++ 8-9_rec.cpp -o 8-9_rec
	g++ 8-9_dp.cpp -o 8-9_dp
8-9_rec : 8-9_rec.cpp
	g++ 8-9_rec.cpp -o 8-9_rec
8-9_dp : 8-9_dp.cpp
	g++ 8-9_dp.cpp -o 8-9_dp
clean:
	rm -f 8-9_rec 8-9_dp
